base_url = "https://techmunchies.net"
compile_sass = true
title = "techmunchies"
description = "Hi! I am Mario and this is my personal/company website."
generate_feeds = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

build_search_index = true
theme = "radion"

[markdown]
highlight_code = true
highlight_theme = "solarized-dark"
insert_anchor_links = "heading"

[search]
index_format = "elasticlunr_json"

[extra]
author = "Mario"
github = "https://github.com/mariolopjr"
twitter = "@mariolopjr"
radion_menu = [
    {url = "$BASE_URL/", name = "home"},
    {url = "$BASE_URL/blog", name = "blog"},
    {url = "$BASE_URL/categories", name = "categories"},
    {url = "$BASE_URL/tags", name = "tags"},
]
radion_title = "techmunchies"

# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax support
latex = false

# Enable search bar
enable_search = true

# Light/Dark Mode set
theme = "toggle"

# Whether to display favicon
favicon = true

# Giscus comment support
comments = false

# Post revision history
revision_history = false
