base_url = "https://techmunchies.net"
theme = "terminus"

title = "techmunchies"
description = ""

compile_sass = true
minify_html = true

build_search_index = true
default_language = "en"
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "mario"

taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true, paginate_by = 10 },
]

[markdown]
highlight_code = true

[extra]
copyright = "© $YEAR techmunchies :: <span>powered by <a target=\"_blank\" href=\"https://www.getzola.org\">zola</a></span> :: <span>theme by <a target=\"_blank\" href=\"https://eyalkalderon.com\">ebkalderon</a></span>"
header_title = "techmunchies"
show_default_author = false

main_menu = [
    { name = "home", url = "@/_index.md", trailing_slash = true },
    { name = "thoughts", url = "@/thoughts/_index.md", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    # { name = "projects", url = "@/projects/_index.md", trailing_slash = true },
    # { name = "about", url = "@/about/_index.md", trailing_slash = true },
    # { name = "résumé", url = "resume.pdf", new_tab = true },
    { name = "rss", url = "rss.xml" },
]

socials = [
    { name = "github", url = "https://github.com/mariolopjr" },
    # { name = "mastodon", url = "https://mastodon.org/@mariolopjr" },
]
